### ISSUE TITLE
Dynamic fields exporting

### ISSUE THREAD

**Issue by fntlnz** [influxdata/nginx-influxdb-module#11]
Talking with @aledbf he suggested that this module could enrich the request metric with custom fields taken from nginx variables set from the user or from nginx itself.

This can be extremely useful for example in a kubernetes cluster by using this module integrated in the [nginx ingress](https://github.com/kubernetes/ingress-nginx) to expose things like the namespace, the ingress or the service names.

The idea is to replicate here the behavior of this lua script in the form of an hashmap called `dynamicfields` to the [request metric](https://github.com/influxdata/nginx-influxdb-module/blob/master/src/ngx_http_influxdb_metric.h#L10-L21)

E.g:

```
{
    "namespace": "namespace",
    "ingress": "ingress_name",
    "service": "service_name"
}
```

**Comment by aledbf** [comment]
@fntlnz any update on this?

**Comment by fntlnz** [comment]
@aledbf I'm working on this.

I'm adding a new configuration directive `influxdb_fields` that is just a kv bucket with custom values from the user.

The final configuration looks like this.

```
influxdb_fields {
  namespace "myns"
  cluster "mycluster"
  ingress_name "example"
}
```

Still need some love to be debugged and tested from my side then I'll open a pr in the next days.
